export const DataCardP = [
  {
    idCard: 1,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p2.png",
    PageProjects: "/Projects/1",
    h3Card: "Headphones selling site",
    pCard: "Html-Css3-Vanilla javscript",
    demoProject: "https://abdalrhman112244.github.io/abdalrhmanberkdar/",
    iconDemo: "/assets/img/i1.svg",
  },
  {
    idCard: 2,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p1.png",
    PageProjects: "/Projects/2",
    h3Card: "Travel site",
    pCard: "React.js",
    demoProject: "https://abdalrhman112244.github.io/react_project1/",
    iconDemo: "/assets/img/i1.svg",
  },
  {
    idCard: 3,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p3.png",
    PageProjects: "/Projects/3",
    h3Card: "Rock paper scissors game",
    pCard: "Html-Css3-Vanilla javscript",
    demoProject: "https://abdalrhman112244.github.io/JS-project-8/",
    iconDemo: "/assets/img/i1.svg",
  },
  {
    idCard: 4,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p4.png",
    PageProjects: "/Projects/4",
    h3Card: "Personal website",
    pCard: "Html-Css3-Vanilla javscript",
    demoProject: "https://abdalrhman112244.github.io/MyProtfoilo/",
    iconDemo: "/assets/img/i1.svg",
  },
  {
    idCard: 5,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p5.png",
    PageProjects: "/Projects/5",
    h3Card: "Educational Platform",
    pCard: "Html-Css3-Vanilla javscript",
    demoProject: "https://abdalrhman112244.github.io/task4-2/",
    iconDemo: "/assets/img/i1.svg",
  },
  {
    idCard: 6,
    gitHubEmail: "https://github.com/abdalrhman112244",
    imgPriject: "/assets/img/p6.png",
    PageProjects: "/Projects/6",
    h3Card: "Mobile phone sales site",
    pCard: "Html-Css3-Vanilla javscript",
    demoProject: "https://abdalrhman112244.github.io/Task5-1-2/",
    iconDemo: "/assets/img/i1.svg",
  },
];
